### ISSUE TITLE
Prompt for MOS password

### ISSUE THREAD

**Issue by iversond** [psadmin-io/ps-vagabond#11]
Add an option to prompt for the MOS account password, or set the password in an environment variable.

**Comment by iversond** [comment]
I see in the current version the `config.rb` file has a section for setting MOS Username/Password via environment variables. Would it be possible/worth the effort to also offer an option to prompt for MOS credentials?

**Comment by jrbing** [comment]
I definitely think this would be a nice feature, but I'm not quite sure what the best way to go about implementing it would be. It looks like other people have [tried doing the same thing](https://github.com/mitchellh/vagrant/issues/2662), and ended up either using environment variables or checking the local '.vagrant' directory to see if the machine had been provisioned or not.  

I'm thinking I might do a bit more research into what it would take to accomplish this by writing a Vagrant plugin.  It would unfortunately require the additional step of installing the plugin, but it could also open up additional possibilities for added functionality.

**Comment by iversond** [comment]
Using env vars is a good solution instead of prompting. Closing this request.
